services:
  backend:
    build: 
      context: ./backend
    container_name: yt_clipper_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/output:/app/output
      - ./backend/temp:/app/temp
      - ./backend/clips:/app/clips
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL:-numanarif.videos@gmail.com}
      - BASE_URL=${BASE_URL:-http://136.110.35.155:8080}
    restart: always

  frontend:
    build: 
      context: ./frontend
    container_name: yt_clipper_frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: always
